const dogs = [
  {
    id: 'dog1',
    name: 'Bella',
    breed: 'Bulldog',
    imageUrl: 'https://secure.img2-fg.wfcdn.com/im/71066008/compr-r85/4307/43074606/sitting-sleepy-bulldog-puppy-statue.jpg',
    favTreat: '',
    favToy: '',
    description: '',
  },
  {
    id: 'dog2',
    name: 'Daisy',
    breed: 'Labrador Retriever ',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/2/26/YellowLabradorLooking_new.jpg',
    favTreat: '',
    favToy: '',
    description: '',
  },
  {
    id: 'dog3',
    name: 'Molly',
    breed: 'Chihuahua',
    imageUrl: 'https://d17fnq9dkz9hgj.cloudfront.net/breed-uploads/2018/08/chihuahua-detail.jpg?bust=1535565487&width=355',
    favTreat: '',
    favToy: '',
    description: '',
  },
  {
    id: 'dog4',
    name: 'Maggie',
    breed: 'Great Dane',
    imageUrl: 'https://s3.amazonaws.com/cdn-origin-etr.akc.org/wp-content/uploads/2017/11/12232617/Great-Dane-Care.jpg',
    favTreat: '',
    favToy: '',
    description: '',
  },
  {
    id: 'dog5',
    name: 'Sonny',
    breed: 'Siberian Husky',
    imageUrl: 'https://i.pinimg.com/originals/c5/2c/a3/c52ca31e872d03239f008b0c88073227.jpg',
    favTreat: '',
    favToy: '',
    description: '',
  },
  {
    id: 'dog6',
    name: 'Bandit',
    breed: 'Pug',
    imageUrl: 'https://d17fnq9dkz9hgj.cloudfront.net/breed-uploads/2018/08/pug-detail.jpg?bust=1535566394&width=355',
    favTreat: '',
    favToy: '',
    description: '',
  },
  {
    id: 'dog7',
    name: 'Lola',
    breed: 'German Sherperd',
    imageUrl: 'https://www.ctvsh.com/sites/default/files/styles/large/adaptive-image/public/german-shepherd-dog-breed-info.jpg?itok=mPeDrQWU',
    favTreat: '',
    favToy: '',
    description: '',
  },
  {
    id: 'dog8',
    name: 'Lucy',
    breed: 'Poodle',
    imageUrl: 'https://lasvegas-k9.com/content/images/thumbs/0006380_poodle_550.jpeg',
    favTreat: '',
    favToy: '',
    description: '',
  },
  {
    id: 'dog9',
    name: 'Cooper',
    breed: 'Golden Retriever',
    imageUrl: 'https://d17fnq9dkz9hgj.cloudfront.net/breed-uploads/2018/08/golden-retriever-detail.jpg?bust=1535565857&width=355',
    favTreat: '',
    favToy: '',
    description: '',
  },
  {
    id: 'dog10',
    name: 'Rocky',
    breed: 'Pitbull',
    imageUrl: 'https://i.pinimg.com/736x/c7/ce/3b/c7ce3bd49c7e97497eb7f3bea352ce7e.jpg',
    favTreat: '',
    favToy: '',
    description: '',
  },
  {
    id: 'dog11',
    name: 'Mandy',
    breed: 'Beagle',
    imageUrl: 'https://d17fnq9dkz9hgj.cloudfront.net/breed-uploads/2018/08/beagle-detail.jpg?bust=1535565158&width=355',
    favTreat: '',
    favToy: '',
    description: '',
  },
  {
    id: 'dog12',
    name: 'Luna',
    breed: 'Bichon Frise',
    imageUrl: 'https://cdn3-www.dogtime.com/assets/uploads/gallery/bichon-frise-dog-breed-pictures/1-sitting.jpg',
    favTreat: '',
    favToy: '',
    description: '',
  },
];

export default dogs;
